### ISSUE TITLE
fix web viewer to work also on Safari [OSX]

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/dSpaceX#90]
Not sure why things don't work in Safari. 
Our 3d crystals gui is based in THREE.js, which works on Safari.

**Comment by kylinmb** [comment]
Shireen and I agreed in the beginning that we would only support a single browser and we selected Chrome. However, because of React and the use of babel, it is highly likely we will work cross-platform. 

That being said, I ran both the master branch and my branch improve_drawer_apperance in safari and was unable to reproduce this issue i.e. the crystal view works for me; see attachment. 

If you can provide reproducible steps I will attempt to fix it. 

![Screen Shot 2020-04-02 at 9 26 24 AM](https://user-images.githubusercontent.com/17341528/78267771-8f036d80-74c4-11ea-9e53-fb44cc453952.png)

**Comment by cchriste** [comment]
Oh, it wasn't working before so I created this issue. Looks like it's fine now.
